site_name: Cloudpi AI User Guide
site_url: https://doc.cloudpi.ai
theme:
  # custom_dir: overrides
  name: material
  logo: images/cp-logo.png
  favicon: images/favicon.png
  font:
    text: Poppins
    # text: 0px
  custom_dir: custom_theme    
  
  features:
    # - toc.integrate 
    # - announce.dismiss
    # - navigation.tabs 
    - navigation.sections 
    - navigation.sidebar.main
    - navigation.sidebar.collapse
    - navigation.top   
    - navigation.sections 
    - navigation.instant
    - icons    
    - icon_links 
    - search.suggest 
    - search.highlight
    - content.tabs.link    
    - content.code.annotation     
    - content.code.copy 
    - toc.follow
    # - navigation.footer
    - content.tabs.link 
    - navigation.path   
    # - header.autohide 

  
  
  language: en
  palette:
        primary: 'white'
        # primary: Dark moderate violet
        accent: deep purple

plugins:
  - glightbox

nav:
    - '<i class="fa fa-info-circle"></i>  Introduction': index.md
    - '<i class="fa fa-rocket" aria-hidden="true"></i> Getting Started': GettingStarted.md
    - '<i class="fa fa-home" aria-hidden="true"></i> Landing Page': homepage.md
    - '<i class="fa fa-universal-access"></i> RBAC': rbac.md
    - '<i class="fa fa-lock" aria-hidden="true"></i> Security': security.md
    - '<i class="fa fa-wrench"></i> Workspace Settings': workspace.md
    - '<i class="fa fa-bell" aria-hidden="true"></i> Alerts & Notifications': AlertsNotifications.md
    - '<i class="fa fa-user-cog" aria-hidden="true"></i> Admin Settings': AdminSetting.md
    - '&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-shield-alt" aria-hidden="true"></i> Global Policy Settings': GlobalPolicies.md
    #- '<i class="fa fa-users" aria-hidden="true"></i> Team Collaboration': teamcollaboration.md
    - '<i class="fa fa-th-large" aria-hidden="true"></i> Dashboards' : Dashboards.md
    - '<i class="fa fa-cloud" aria-hidden="true"></i>  Billing Hub' : MultiCloudBillingHub.md
    - '<i class="fa fa-cloud-upload-alt" aria-hidden="true"></i> Cloud Onboarding': CloudOnboarding.md
    - '<i class="fa fa-plug" aria-hidden="true"></i> Provider Connections':
        - AWS: ConnectAWS.md
        - Azure: ConnectAzure.md
        - GCP: ConnectGCP.md
    - '<i class="fa fa-database" aria-hidden="true"></i> Billing Exports': BillingExports.md
    - '<i class="fa fa-sync-alt" aria-hidden="true"></i> Data Refresh & Dimensions': DataRefreshAndDimensions.md
    #
    - '<i class="fa fa-arrow-up" aria-hidden="true"></i> CloudPi Optimizations': CloudPiOptimisations.md
    #
    - '<i class="fa fa-dollar-sign" aria-hidden="true"></i> Financials': Financials.md
    - '<i class="fa fa-coins" aria-hidden="true"></i> Cost Types': CostTypes.md
    - '<i class="fa fa-sitemap" aria-hidden="true"></i> Cost Assignment': CostAssignment.md
    - '<i class="fa fa-tag" aria-hidden="true"></i> Tag Management' : TagManagement.md
    - '<i class="fa fa-cogs" aria-hidden="true"></i> Integrations': Integrations.md
    - '<i class="fa fa-link" aria-hidden="true"></i> Integrations Catalog': IntegrationsCatalog.md
    - '<i class="fa fa-shield-alt" aria-hidden="true"></i> SSO Setup': SSOSetup.md
    - '<i class="fa fa-magic" aria-hidden="true"></i> Automation Overview': AutomationOverview.md
    - '&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-clipboard-list" aria-hidden="true"></i> Policies & Workflows': AutomationPolicies.md
    - '&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-clock" aria-hidden="true"></i> VM Scheduler': AutomationVMScheduler.md
    - '<i class="fa fa-user-shield" aria-hidden="true"></i> Service Accounts': ServiceAccounts.md
    - '<i class="fa fa-users" aria-hidden="true"></i> User Management': UserManagement.md
    - '<i class="fa fa-tasks" aria-hidden="true"></i> Task Management': TaskManagement.md
    - '<i class="fa fa-ticket-alt" aria-hidden="true"></i> Ticketing': Ticketing.md
    - '<i class="fa fa-life-ring" aria-hidden="true"></i> Troubleshooting': Troubleshooting.md
    - '<i class="fa fa-book" aria-hidden="true"></i> Glossary': Glossary.md


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css
  # - custom_theme/assets/stylesheet1/custom.css
  - stylesheets/custom.css
  # - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap-icons.svg
  # - https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0
  # - https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined
  # - bootstrap.min.css


use_directory_urls: true

markdown_extensions:
  # - toc:
  #     permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details       
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2026 <a href="https://cloudpi.ai" target="_blank" rel="noopener">PurpleData Inc DBA Cloudpi</a>
